app/posts/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app/posts/blueprint.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
from flask import Blueprint
from flask import render_template

from models import Post, Tag
from .forms import PostForm
from app import db
from flask import redirect, url_for, request
from flask_security import login_required
# from sqlalchemy.sql.functions import current_timestamp
# created = db.Column(db.DateTime, default=current_timestamp())

posts = Blueprint('posts', __name__, template_folder='templates')



# http://flask_blog.localhost:5020/blog/create
@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        if title:
            try:
                post = Post(title=title, body=body)
                db.session.add(post)
                db.session.commit()
            except:
                print('Something is Wrong')
            return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q', u'')

    page = request.args.get('page')
    page = int(page) if page and page.isdigit() else 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) # .all()
    else:
        posts = Post.query.order_by(Post.created.desc())  # .all()

    pages = posts.paginate(page=page, per_page=5)
    return render_template('posts/index.html', pages=pages, q=q)


# http://flask_blog.localhost:5020/blog/first-post
@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


# http://flask_blog.localhost:5020/blog/tag/python
@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts # .all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    New post
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Create</button>
        </form>
    </div>
{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit post
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Edit</button>
        </form>
    </div>
{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}
    {% for post in pages.items %}
        <p>
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}"> {{ post.title }} </a>
        </p>
    {% endfor%}

    {# локальная переменная содержащая строку поиска для сохранения и передачи в ссылках #}
    {# или просто {% set q='&q=%s' % q %}  но тогда параметр q= будет всегда присутствовать #}
    {% if q %} {% set q='&q=%s' % q %} {% endif %}
    <nav>
      <ul class="pagination">
        <li {% if not pages.has_prev %} class="page-item disabled" {% else %} class="page-item" {% endif %} >
          <a class="page-link" href="./?page={{ pages.prev_num }}{{ q }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% for page in pages.iter_pages() %}
            <li {% if page == pages.page %} class="page-item active" {% else %} class="page-item" {% endif %} >
                <a class="page-link" href="./?page={{ page }}{{ q }}"> {{ page }} </a>
            </li>
        {% endfor%}

        <li {% if not pages.has_next %} class="page-item disabled" {% else %} class="page-item" {% endif %} >
          <a class="page-link" href="./?page={{ pages.next_num }}{{ q }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <a class="btn btn-primary btn-sm" href="{{ url_for('posts.tag_detail', slug=tag.slug) }}" role="button">{{ tag.name }}</a>
        {% endfor %}
    </div>

    <div class="main-content">
        {{ post.body }}
    </div>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag
{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </div>
    {% endfor %}
{% endblock %}